### ISSUE TITLE
Bug: Vercel deployment fails due to the Contributor Script

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#131]
### Describe the bug.

We use a Node Script during the post-install process to fetch the list of contributors for the community website. However during the Vercel build process, after a PR gets merged, the deployment fails due to a bug in the Node script. The deployments have to be manually triggered to invalidate the cache before proceeding.

### Describe the steps to reproduce the behavior.

The logs are shared below and it can be emulated on a local install and build run.

### Expected behavior.

We would ideally want this bug to be fixed during the build process so that we don't have to manually trigger the build process. 

### Operating Environment

Chrome Version 93.0.4577.82 (Official Build) (64-bit); Vercel

### Additional Information

Build Logs:

```sh
09:00:14.463  	Cloning github.com/moja-global/community-website (Branch: main, Commit: 18e5b0b)
09:00:15.322  	Cloning completed: 858.116ms
09:00:15.361  	Analyzing source code...
09:00:16.682  	Installing build runtime...
09:00:18.917  	Build runtime installed: 2.235s
09:00:21.502  	Looking up build cache...
09:00:24.639  	Build cache downloaded [43.93 MB]: 2935.354ms
09:00:25.927  	Detected package.json
09:00:25.927  	Installing dependencies...
09:00:26.250  	yarn install v1.22.11
09:00:26.368  	[1/4] Resolving packages...
09:00:27.089  	success Already up-to-date.
09:00:27.093  	$ node ./fetchContributors.js
09:00:27.551  	/vercel/path0/website/fetchContributors.js:27
09:00:27.551  	    for (const item of content) {
09:00:27.551  	                       ^
09:00:27.552  	TypeError: content is not iterable
09:00:27.552  	    at Request._callback (/vercel/path0/website/fetchContributors.js:27:24)
09:00:27.552  	    at Request.self.callback (/vercel/path0/website/node_modules/request/request.js:185:22)
09:00:27.552  	    at Request.emit (events.js:400:28)
09:00:27.552  	    at Request.<anonymous> (/vercel/path0/website/node_modules/request/request.js:1154:10)
09:00:27.552  	    at Request.emit (events.js:400:28)
09:00:27.553  	    at IncomingMessage.<anonymous> (/vercel/path0/website/node_modules/request/request.js:1076:12)
09:00:27.553  	    at Object.onceWrapper (events.js:519:28)
09:00:27.553  	    at IncomingMessage.emit (events.js:412:35)
09:00:27.553  	    at endReadableNT (internal/streams/readable.js:1334:12)
09:00:27.553  	    at processTicksAndRejections (internal/process/task_queues.js:82:21)
09:00:27.565  	error Command failed with exit code 1.
09:00:27.566  	info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
09:00:27.595  	Error: Command "yarn install" exited with 1
```

**Comment by sandeep-v1404** [comment]
Hey Harsh. Can you assign it to me? @HarshCasper
